FROM ubuntu:18.10 as build

FROM ubuntu:18.10 as release

RUN apt update \
    && apt install -yqq software-properties-common \
    && apt upgrade -yqq 

RUN add-apt-repository ppa:obsproject/obs-studio \
    && apt update \
    && apt install -yqq obs-studio 
