#! /bin/sh

image="obs_nvidia:local"
name="obs_nvidia"
groups="video"
devices="/dev/video* /dev/dri /dev/snd"
volumes="/etc/group /run/user/$(id -u) /tmp/.X11-unix /etc/machine-id /var/lib/dbus $HOME"
env="DISPLAY HOME XDG_RUNTIME_DIR"
docker_extra="" # "-it"
extra=""
stdout="/dev/null"
stderr="/dev/null"

arglist(){
    argname=$1
    shift
    for i in $@; do
        echo $argname $i;
    done
}

bindlist() {
    echo $@ | sed -E 's/(\S+)/type=bind,source=\1,target=\1/g'
}

getgroup(){
    echo $(getent group $@| awk -F: '{print $3}')
}

envlist(){
    eval echo $(echo $@ | sed -E 's/(\S+)/\1=$\1/g')
}

arg_group=$(arglist --group-add $(getgroup ${groups}))
arg_device=$(arglist --device ${devices})
arg_volume=$(arglist --mount $(bindlist ${volumes}))
arg_env=$(arglist --env $(envlist ${env}))

gid=$(id -g)
uid=$(id -u)
id="${uid}:${gid}"
hostname=$(uname --nodename)

if [ -z $(docker images -q "${image}") ]; then
    docker build -t ${image} .
fi

if [ -z $(docker ps -a --filter "name=${name}" -q) ]; then
	docker run  ${docker_extra}	\
	    --runtime=nvidia        	\
	    --name=${name}		\
	    --hostname=${hostname}  	\
	    --user ${id}            	\
	    ${arg_device}           	\
	    ${arg_volume}           	\
	    ${arg_group}            	\
	    ${arg_env}              	\
	    ${image}		    	\
	    ${extra} 		    	\
	    1> ${stdout}            	\
	    2> ${stderr}
else
	docker start ${name}		\
	    1> ${stdout}            	\
	    2> ${stderr}
fi
